use RetailSalesDB;

-- 1.	What is the total number of orders placed per year?
SELECT 
    YEAR(Order_Date) AS Order_year,
    COUNT(Order_Number) AS total_orders
FROM
    sales
GROUP BY YEAR(Order_Date)
ORDER BY total_orders DESC;


-- 2.	What are the total sales (USD) by product category?
SELECT 
    p.Category,
    SUM((s.quantity * p.Unit_Price_USD)) AS total_sales
FROM
    products p
        JOIN
    sales s ON p.ProductKey = s.ProductKey
GROUP BY p.Category
ORDER BY total_sales DESC;

-- 3.	Which 5 customers made the highest number of purchases Quantity?
SELECT 
    c.Name, count(*) AS total_purchases
FROM
    customers c
        JOIN
    sales s ON s.CustomerKey = c.CustomerKey
GROUP BY c.CustomerKey
ORDER BY total_purchases DESC
LIMIT 5;

-- 4.	What is the total quantity sold for each product?
SELECT 
    p.product_Name, SUM(s.quantity) AS total_quantity_sold
FROM
    sales s
        JOIN
    products p ON p.ProductKey = s.ProductKey
GROUP BY product_Name
ORDER BY total_quantity_sold DESC;

-- 5.	List all distinct countries and continents where the customers are located.
SELECT DISTINCT
    country, Continent
FROM
    customers;
    
-- 6.	What is the average delivery time (in days) for each state?
SELECT 
    ROUND(AVG(DATEDIFF(Delivery_Date, Order_Date))) AS average_delivery_time
FROM
    sales;

-- 7.	List top 5 best-selling products Category by unit price sold.
SELECT 
    Category, SUM(Unit_Price_USD) AS unit_price_sold
FROM
    products
GROUP BY Category
ORDER BY unit_sold DESC
LIMIT 5;

-- 8.	What is the total revenue generated by each store?
SELECT 
    st.storeKey,
    SUM(s.Quantity * p.Unit_Price_USD) AS Total_revenue
FROM
    sales s
        JOIN
    stores st ON st.storeKey = s.storeKey
        JOIN
    products p ON p.ProductKey = s.ProductKey
GROUP BY storeKey
ORDER BY Total_revenue DESC;

-- 9.	What is the number of male vs female customers?
SELECT 
    gender, COUNT(*) AS Total_customers
FROM
    customers
GROUP BY gender;


-- 10.	Which product categories are sold in which countries?
SELECT DISTINCT
    p.Category, st.Country
FROM
    Sales s
        JOIN
    Products p ON s.ProductKey = p.ProductKey
        JOIN
    Stores st ON s.StoreKey = st.StoreKey
ORDER BY p.Category , st.Country;
